# SQLite version 3.x
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
#
default: &default
  adapter: mysql2
  encoding: utf8mb4
  charset: utf8mb4
  collation: utf8mb4_general_ci
  reconnect: true
  pool: 5
  socket: /var/lib/mysql/mysql.sock
  username: root
  password: root

development:
  <<: *default
  database: bbs_development

test:
  <<: *default
  database: bbs_test

production:
  <<: *default
  database: bbs_production
